server:
  port: 31001
spring:
  application:
    name: xc-service-mange-cms
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
xc:
  mq:
    rabbitmq:
      exchange: ex_routing_cms_postpage
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/,http://eureka01:50101/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}